name: Test

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Finally? master"
      if: always() && github.ref == 'refs/heads/main'
      env:
        JOB_STATUS: ${{ job.status }}
      run: echo "Finally! Status $JOB_STATUS"

    - name: "Finally? release"
      if: startsWith(github.ref, 'refs/heads/release/')  # Skip for master => development and release/* => master
      env:
        JOB_STATUS: ${{ job.status }}
      run: echo "Finally Release! Status $JOB_STATUS"