name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        if: startsWith(github.head_ref, 'squad-') && endsWith(github.head_ref, '/agenda-deploy')
        run: echo "Running branch name matches"
